# Source: http://rasbt.github.io/mlxtend/user_guide/frequent_patterns/association_rules/

# Example 1 -- Generating Association Rules from Frequent Itemsets

The generate_rules takes dataframes of frequent itemsets as produced by the apriori, fpgrowth, or fpmax functions in mlxtend.association. To demonstrate the usage of the generate_rules method, we first create a pandas DataFrame of frequent itemsets as generated by the fpgrowth function:

In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, fpmax, fpgrowth


dataset = [['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
           ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
           ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]

te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)

frequent_itemsets = fpgrowth(df, min_support=0.6, use_colnames=True)
### alternatively:
#frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)
#frequent_itemsets = fpmax(df, min_support=0.6, use_colnames=True)

frequent_itemsets

support                     itemsets
0       1.0               (Kidney Beans)
1       0.8                       (Eggs)
2       0.6                     (Yogurt)
3       0.6                      (Onion)
4       0.6                       (Milk)
5       0.8         (Kidney Beans, Eggs)
6       0.6       (Yogurt, Kidney Beans)
7       0.6                (Onion, Eggs)
8       0.6        (Onion, Kidney Beans)
9       0.6  (Onion, Kidney Beans, Eggs)
10      0.6         (Milk, Kidney Beans)

The generate_rules() function allows you to (1) specify your metric of interest and (2) the according threshold. Currently implemented measures are confidence and lift. Let's say you are interested in rules derived from the frequent itemsets only if the level of confidence is above the 70 percent threshold (min_threshold=0.7):

In [2]:
from mlxtend.frequent_patterns import association_rules

association_rules(frequent_itemsets, metric="confidence", min_threshold=0.7)

antecedents            consequents  antecedent support  \
0          (Kidney Beans)                 (Eggs)                 1.0   
1                  (Eggs)         (Kidney Beans)                 0.8   
2                (Yogurt)         (Kidney Beans)                 0.6   
3                 (Onion)                 (Eggs)                 0.6   
4                  (Eggs)                (Onion)                 0.8   
5                 (Onion)         (Kidney Beans)                 0.6   
6   (Onion, Kidney Beans)                 (Eggs)                 0.6   
7           (Onion, Eggs)         (Kidney Beans)                 0.6   
8    (Kidney Beans, Eggs)                (Onion)                 0.8   
9                 (Onion)   (Kidney Beans, Eggs)                 0.6   
10                 (Eggs)  (Onion, Kidney Beans)                 0.8   
11                 (Milk)         (Kidney Beans)                 0.6   

    consequent support  support  confidence  lift  leverage  conviction  
0                  0.8      0.8        0.80  1.00      0.00         1.0  
1                  1.0      0.8        1.00  1.00      0.00         inf  
2                  1.0      0.6        1.00  1.00      0.00         inf  
3                  0.8      0.6        1.00  1.25      0.12         inf  
4                  0.6      0.6        0.75  1.25      0.12         1.6  
5                  1.0      0.6        1.00  1.00      0.00         inf  
6                  0.8      0.6        1.00  1.25      0.12         inf  
7                  1.0      0.6        1.00  1.00      0.00         inf  
8                  0.6      0.6        0.75  1.25      0.12         1.6  
9                  0.8      0.6        1.00  1.25      0.12         inf  
10                 0.6      0.6        0.75  1.25      0.12         1.6  
11                 1.0      0.6        1.00  1.00      0.00         inf

# Example 2 -- Rule Generation and Selection Criteria

If you are interested in rules according to a different metric of interest, you can simply adjust the metric and min_threshold arguments . E.g. if you are only interested in rules that have a lift score of >= 1.2, you would do the following:

In [3]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1.2)
rules

antecedents            consequents  antecedent support  \
0                (Onion)                 (Eggs)                 0.6   
1                 (Eggs)                (Onion)                 0.8   
2  (Onion, Kidney Beans)                 (Eggs)                 0.6   
3   (Kidney Beans, Eggs)                (Onion)                 0.8   
4                (Onion)   (Kidney Beans, Eggs)                 0.6   
5                 (Eggs)  (Onion, Kidney Beans)                 0.8   

   consequent support  support  confidence  lift  leverage  conviction  
0                 0.8      0.6        1.00  1.25      0.12         inf  
1                 0.6      0.6        0.75  1.25      0.12         1.6  
2                 0.8      0.6        1.00  1.25      0.12         inf  
3                 0.6      0.6        0.75  1.25      0.12         1.6  
4                 0.8      0.6        1.00  1.25      0.12         inf  
5                 0.6      0.6        0.75  1.25      0.12         1.6

Pandas DataFrames make it easy to filter the results further. Let's say we are ony interested in rules that satisfy the following criteria:

* at least 2 antecedents
* a confidence > 0.75
* a lift score > 1.2

    We could compute the antecedent length as follows:

In [4]:
rules["antecedent_len"] = rules["antecedents"].apply(lambda x: len(x))
rules

antecedents            consequents  antecedent support  \
0                (Onion)                 (Eggs)                 0.6   
1                 (Eggs)                (Onion)                 0.8   
2  (Onion, Kidney Beans)                 (Eggs)                 0.6   
3   (Kidney Beans, Eggs)                (Onion)                 0.8   
4                (Onion)   (Kidney Beans, Eggs)                 0.6   
5                 (Eggs)  (Onion, Kidney Beans)                 0.8   

   consequent support  support  confidence  lift  leverage  conviction  \
0                 0.8      0.6        1.00  1.25      0.12         inf   
1                 0.6      0.6        0.75  1.25      0.12         1.6   
2                 0.8      0.6        1.00  1.25      0.12         inf   
3                 0.6      0.6        0.75  1.25      0.12         1.6   
4                 0.8      0.6        1.00  1.25      0.12         inf   
5                 0.6      0.6        0.75  1.25      0.12         1.6   

   antecedent_len  
0               1  
1               1  
2               2  
3               2  
4               1  
5               1

In [5]:
rules[(rules['antecedent_len'] >= 2) & (rules['confidence'] > 0.75) & (rules['lift'] > 1.2) ]

antecedents consequents  antecedent support  consequent support  \
2  (Onion, Kidney Beans)      (Eggs)                 0.6                 0.8   

   support  confidence  lift  leverage  conviction  antecedent_len  
2      0.6         1.0  1.25      0.12         inf               2

In [6]:
rules[rules['antecedents'] == {'Eggs', 'Kidney Beans'}]

antecedents consequents  antecedent support  consequent support  \
3  (Kidney Beans, Eggs)     (Onion)                 0.8                 0.6   

   support  confidence  lift  leverage  conviction  antecedent_len  
3      0.6        0.75  1.25      0.12         1.6               2

# Example 3 -- Frequent Itemsets with Incomplete Antecedent and Consequent Information
Most metrics computed by association_rules depends on the consequent and antecedent support score of a given rule provided in the frequent itemset input DataFrame. Consider the following example:

In [7]:
import pandas as pd

dict = {'itemsets': [['177', '176'], ['177', '179'],
                     ['176', '178'], ['176', '179'],
                     ['93', '100'], ['177', '178'],
                     ['177', '176', '178']],
        'support':[0.253623, 0.253623, 0.217391,
                   0.217391, 0.181159, 0.108696, 0.108696]}

freq_itemsets = pd.DataFrame(dict)
freq_itemsets

itemsets   support
0       [177, 176]  0.253623
1       [177, 179]  0.253623
2       [176, 178]  0.217391
3       [176, 179]  0.217391
4        [93, 100]  0.181159
5       [177, 178]  0.108696
6  [177, 176, 178]  0.108696

Note that this is a "cropped" DataFrame that doesn't contain the support values of the item subsets. This can create problems if we want to compute the association rule metrics for, e.g., 176 => 177.

For example, the confidence is computed as

confidence(A→C)=support(A→C)support(A),range: [0,1]

But we do not have support(A)
. All we know about "A"'s support is that it is at least 0.253623.

In these scenarios, where not all metric's can be computed, due to incomplete input DataFrames, you can use the support_only=True option, which will only compute the support column of a given rule that does not require as much info:

support(A→C)=support(A∪C),range: [0,1]

"NaN's" will be assigned to all other metric columns:

In [8]:
from mlxtend.frequent_patterns import association_rules

res = association_rules(freq_itemsets, support_only=True, min_threshold=0.1)
res

antecedents consequents  antecedent support  consequent support   support  \
0        (176)       (177)                 NaN                 NaN  0.253623   
1        (177)       (176)                 NaN                 NaN  0.253623   
2        (177)       (179)                 NaN                 NaN  0.253623   
3        (179)       (177)                 NaN                 NaN  0.253623   
4        (176)       (178)                 NaN                 NaN  0.217391   
5        (178)       (176)                 NaN                 NaN  0.217391   
6        (176)       (179)                 NaN                 NaN  0.217391   
7        (179)       (176)                 NaN                 NaN  0.217391   
8        (100)        (93)                 NaN                 NaN  0.181159   
9         (93)       (100)                 NaN                 NaN  0.181159   
10       (177)       (178)                 NaN                 NaN  0.108696   
11       (178)       (177)                 NaN                 NaN  0.108696   
12  (176, 177)       (178)                 NaN                 NaN  0.108696   
13  (176, 178)       (177)                 NaN                 NaN  0.108696   
14  (177, 178)       (176)                 NaN                 NaN  0.108696   
15       (176)  (177, 178)                 NaN                 NaN  0.108696   
16       (177)  (176, 178)                 NaN                 NaN  0.108696   
17       (178)  (176, 177)                 NaN                 NaN  0.108696   

    confidence  lift  leverage  conviction  
0          NaN   NaN       NaN         NaN  
1          NaN   NaN       NaN         NaN  
2          NaN   NaN       NaN         NaN  
3          NaN   NaN       NaN         NaN  
4          NaN   NaN       NaN         NaN  
5          NaN   NaN       NaN         NaN  
6          NaN   NaN       NaN         NaN  
7          NaN   NaN       NaN         NaN  
8          NaN   NaN       NaN         NaN  
9          NaN   NaN       NaN         NaN  
10         NaN   NaN       NaN         NaN  
11         NaN   NaN       NaN         NaN  
12         NaN   NaN       NaN         NaN  
13         NaN   NaN       NaN         NaN  
14         NaN   NaN       NaN         NaN  
15         NaN   NaN       NaN         NaN  
16         NaN   NaN       NaN         NaN  
17         NaN   NaN       NaN         NaN

In [9]:
res = res[['antecedents', 'consequents', 'support']]
res

antecedents consequents   support
0        (176)       (177)  0.253623
1        (177)       (176)  0.253623
2        (177)       (179)  0.253623
3        (179)       (177)  0.253623
4        (176)       (178)  0.217391
5        (178)       (176)  0.217391
6        (176)       (179)  0.217391
7        (179)       (176)  0.217391
8        (100)        (93)  0.181159
9         (93)       (100)  0.181159
10       (177)       (178)  0.108696
11       (178)       (177)  0.108696
12  (176, 177)       (178)  0.108696
13  (176, 178)       (177)  0.108696
14  (177, 178)       (176)  0.108696
15       (176)  (177, 178)  0.108696
16       (177)  (176, 178)  0.108696
17       (178)  (176, 177)  0.108696

In [10]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, fpmax, fpgrowth
from mlxtend.frequent_patterns import association_rules


dataset = [['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
           ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
           ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]

te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)

frequent_itemsets = fpgrowth(df, min_support=0.6, use_colnames=True)
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1.2)
rules

antecedents            consequents  antecedent support  \
0                (Onion)                 (Eggs)                 0.6   
1                 (Eggs)                (Onion)                 0.8   
2  (Onion, Kidney Beans)                 (Eggs)                 0.6   
3   (Kidney Beans, Eggs)                (Onion)                 0.8   
4                (Onion)   (Kidney Beans, Eggs)                 0.6   
5                 (Eggs)  (Onion, Kidney Beans)                 0.8   

   consequent support  support  confidence  lift  leverage  conviction  
0                 0.8      0.6        1.00  1.25      0.12         inf  
1                 0.6      0.6        0.75  1.25      0.12         1.6  
2                 0.8      0.6        1.00  1.25      0.12         inf  
3                 0.6      0.6        0.75  1.25      0.12         1.6  
4                 0.8      0.6        1.00  1.25      0.12         inf  
5                 0.6      0.6        0.75  1.25      0.12         1.6

and we want to remove the rule "(Onion, Kidney Beans) -> (Eggs)". In order to to this, we can define selection masks and remove this row as follows:

In [11]:
antecedent_sele = rules['antecedents'] == frozenset({'Onion', 'Kidney Beans'}) # or  frozenset({'Kidney Beans', 'Onion'})
consequent_sele = rules['consequents'] == frozenset({'Eggs'})
final_sele = (antecedent_sele & consequent_sele)

rules.loc[ ~final_sele ]

antecedents            consequents  antecedent support  \
0               (Onion)                 (Eggs)                 0.6   
1                (Eggs)                (Onion)                 0.8   
3  (Kidney Beans, Eggs)                (Onion)                 0.8   
4               (Onion)   (Kidney Beans, Eggs)                 0.6   
5                (Eggs)  (Onion, Kidney Beans)                 0.8   

   consequent support  support  confidence  lift  leverage  conviction  
0                 0.8      0.6        1.00  1.25      0.12         inf  
1                 0.6      0.6        0.75  1.25      0.12         1.6  
3                 0.6      0.6        0.75  1.25      0.12         1.6  
4                 0.8      0.6        1.00  1.25      0.12         inf  
5                 0.6      0.6        0.75  1.25      0.12         1.6